start /B python36 super_selenium_a.py
start /B python36 super_selenium_b.py
start /B python36 super_selenium_c.py
start /B python36 super_selenium_d.py
start /B python36 super_selenium_e.py
start /B python36 super_selenium_f.py
start /B python36 super_selenium_g.py
start /B python36 super_selenium_h.py
start /B python36 super_selenium_i.py
start /B python36 super_selenium_j.py